<!--
/**
 * Created By : Vtearit
 */
-->
<!DOCTYPE html>
<html>
	<body>
		<div class="carousel-wrap">
		  <div class="owl-carousel">
		    <div class="item"><img src="http://placehold.it/350x300?text=1"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=2"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=3"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=4"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=5"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=6"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=7"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=8"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=9"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=10"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=11"></div>
		    <div class="item"><img src="http://placehold.it/350x300?text=12"></div>
		  </div>
		</div>
	</body>
</html>