<?php
/** @var \AHT\Delivery\Block\Template $block */
    $order = $block->getOrder();
?>
<div class="admin__page-section-item order-payment-method">
    <div class="admin__page-section-item-title">
        <span class="title">Delivery Information</span>
        <span><?= /* @noEscape */ $block->getEditLink(); ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <p><span><label>Date : </label></span><?= $order->getDeliveryDate()?></p>
        <p><span><label>Note : </label></span><?= $order->getDeliveryNote()?></p>
    </div>