<?php

/** @var \AHT\Knockoutjs\Block\Template $block */
?>

<div id='fastorder-template' data-bind="scope: 'fastorder'">
    <!-- ko template: getTemplate() -->
    <!-- /ko  -->
    <script type="text/x-magento-init">
        {
        "#fastorder-template": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "fastorder": {
                        "component": "AHT_Knockoutjs/js/fastorder",
                        "template" : "AHT_Knockoutjs/fastorder"
                    }
                }
            }
        }
    }
</script>
</div>
